# Introduction
This notebook provides example calculations for Recurrent Neural Networks (RNN), Long Short-Term Memory (LSTM), and Gated Recurrent Unit (GRU) networks. These examples are designed for teaching purposes and include step-by-step explanations.

In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x) )

# Recurrent Neural Network (RNN) Example


In [5]:


# Define the input vectors
P = np.array([1, 0, 0, 0])
A = np.array([0, 1, 0, 0])
R = np.array([0, 0, 1, 0])
K = np.array([0, 0, 0, 1])

# Define the weight matrices and bias vector
W_x = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2],
    [1.3, 1.4, 1.5, 1.6]
])
W_h = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2],
    [1.3, 1.4, 1.5, 1.6]
])
b = np.array([0.1, 0.2, 0.3, 0.4])

# Initial hidden state
h_0 = np.zeros(4)

# Function to calculate the hidden state
def rnn_step(x, h_prev):
    return np.tanh( np.dot(W_x, x) + np.dot(W_h, h_prev) + b )

# Calculate the hidden states for each input
h_1 = rnn_step(P, h_0)
h_2 = rnn_step(A, h_1)
h_3 = rnn_step(R, h_2)
h_4 = rnn_step(K, h_3)

h_1, h_2, h_3, h_4


(array([0.19737532, 0.60436778, 0.83365461, 0.93540907]),
 array([0.78752106, 0.98887785, 0.99947397, 0.99997525]),
 array([0.88013356, 0.99771501, 0.99995896, 0.99999926]),
 array([0.90287178, 0.99831338, 0.99997209, 0.99999954]))

# Long Short-Term Memory (LSTM) Example


In [6]:
import numpy as np

# Define the input vectors
P = np.array([1, 0, 0, 0])
A = np.array([0, 1, 0, 0])
R = np.array([0, 0, 1, 0])
K = np.array([0, 0, 0, 1])

# Define the weight matrices and bias vectors
W_f = np.random.rand(4, 4)
W_i = np.random.rand(4, 4)
W_c = np.random.rand(4, 4)
W_o = np.random.rand(4, 4)
U_f = np.random.rand(4, 4)
U_i = np.random.rand(4, 4)
U_c = np.random.rand(4, 4)
U_o = np.random.rand(4, 4)
b_f = np.random.rand(4)
b_i = np.random.rand(4)
b_c = np.random.rand(4)
b_o = np.random.rand(4)

# Initial hidden state and cell state
h_0 = np.zeros(4)
c_0 = np.zeros(4)

# Function to calculate the LSTM cell
def lstm_step(x, h_prev, c_prev):
    f_t = sigmoid(np.dot(W_f, x) + np.dot(U_f, h_prev) + b_f)
    i_t = sigmoid(np.dot(W_i, x) + np.dot(U_i, h_prev) + b_i)
    c_tilde = np.tanh(np.dot(W_c, x) + np.dot(U_c, h_prev) + b_c)
    c_t = f_t * c_prev + i_t * c_tilde
    o_t = sigmoid(np.dot(W_o, x) + np.dot(U_o, h_prev) + b_o)
    h_t = o_t * np.tanh(c_t)
    return h_t, c_t

# Calculate the hidden states and cell states for each input
h_1, c_1 = lstm_step(P, h_0, c_0)
h_2, c_2 = lstm_step(A, h_1, c_1)
h_3, c_3 = lstm_step(R, h_2, c_2)
h_4, c_4 = lstm_step(K, h_3, c_3)

h_1, h_2, h_3, h_4


(array([0.41289546, 0.43230163, 0.19200078, 0.28364333]),
 array([0.73499519, 0.74403036, 0.49832367, 0.59905013]),
 array([0.81081682, 0.80071203, 0.77908564, 0.86504419]),
 array([0.85527892, 0.89398195, 0.88919778, 0.96078936]))

# Gated Recurrent Unit (GRU) Example


In [7]:
import numpy as np

# Define the input vectors
P = np.array([1, 0, 0, 0])
A = np.array([0, 1, 0, 0])
R = np.array([0, 0, 1, 0])
K = np.array([0, 0, 0, 1])

# Define the weight matrices and bias vectors
W_z = np.random.rand(4, 4)
W_r = np.random.rand(4, 4)
W_h = np.random.rand(4, 4)
U_z = np.random.rand(4, 4)
U_r = np.random.rand(4, 4)
U_h = np.random.rand(4, 4)
b_z = np.random.rand(4)
b_r = np.random.rand(4)
b_h = np.random.rand(4)

# Initial hidden state
h_0 = np.zeros(4)

# Function to calculate the GRU cell
def gru_step(x, h_prev):
    z_t = sigmoid(np.dot(W_z, x) + np.dot(U_z, h_prev) + b_z)
    r_t = sigmoid(np.dot(W_r, x) + np.dot(U_r, h_prev) + b_r)
    h_tilde = np.tanh(np.dot(W_h, x) + np.dot(U_h, r_t * h_prev) + b_h)
    h_t = (1 - z_t) * h_prev + z_t * h_tilde
    return h_t

# Calculate the hidden states for each input
h_1 = gru_step(P, h_0)
h_2 = gru_step(A, h_1)
h_3 = gru_step(R, h_2)
h_4 = gru_step(K, h_3)

h_1, h_2, h_3, h_4


(array([0.56523509, 0.40247428, 0.73458357, 0.42650638]),
 array([0.92475416, 0.92958679, 0.9590722 , 0.85704048]),
 array([0.9955618 , 0.98948952, 0.99585142, 0.98821207]),
 array([0.99843562, 0.99777125, 0.99903517, 0.99412206]))